version: '3.3'

services:
  mysql:
    image: mysql:8.0.32
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: {}
